import React from 'react';
import { create } from 'zustand';

type Locale = 'zh-CN' | 'en-US';

type Dictionary = Record<string, Record<Locale, string>>;

const dictionary: Dictionary = {
  'navbar.brand': { 'zh-CN': 'AICenter 控制台', 'en-US': 'AICenter Console' },
  'navbar.profile': { 'zh-CN': '个人资料', 'en-US': 'Profile' },
  'navbar.settings': { 'zh-CN': '设置', 'en-US': 'Settings' },
  'navbar.logout': { 'zh-CN': '退出登录', 'en-US': 'Logout' },
  'navbar.logoutSuccess': { 'zh-CN': '已退出登录', 'en-US': 'Logged out successfully' },

  'sidebar.dashboard': { 'zh-CN': '仪表盘', 'en-US': 'Dashboard' },
  'sidebar.servers': { 'zh-CN': '服务器', 'en-US': 'Servers' },
  'sidebar.docker': { 'zh-CN': 'Docker', 'en-US': 'Docker' },
  'sidebar.agents': { 'zh-CN': '智能体', 'en-US': 'Agents' },
  'sidebar.tasks': { 'zh-CN': '任务', 'en-US': 'Tasks' },
  'sidebar.monitor': { 'zh-CN': '监控', 'en-US': 'Monitor' },
  'sidebar.notifications': { 'zh-CN': '通知', 'en-US': 'Notifications' },
  'sidebar.approvals': { 'zh-CN': '待审批', 'en-US': 'Approvals' },
  'sidebar.audit': { 'zh-CN': '审计日志', 'en-US': 'Audit Log' },
  'sidebar.ai': { 'zh-CN': 'AI 模型', 'en-US': 'AI Models' },
  'sidebar.settings': { 'zh-CN': '设置', 'en-US': 'Settings' },

  'login.title': { 'zh-CN': 'AICenter 登录', 'en-US': 'AICenter Login' },
  'login.username': { 'zh-CN': '用户名', 'en-US': 'Username' },
  'login.password': { 'zh-CN': '密码', 'en-US': 'Password' },
  'login.submit': { 'zh-CN': '登录', 'en-US': 'Login' },
  'login.loading': { 'zh-CN': '登录中...', 'en-US': 'Logging in...' },
  'login.error.empty': { 'zh-CN': '请输入用户名和密码', 'en-US': 'Please enter username and password' },
  'login.error.invalid': { 'zh-CN': '用户名或密码错误', 'en-US': 'Invalid username or password' },

  'dashboard.title': { 'zh-CN': '仪表盘', 'en-US': 'Dashboard' },
  'dashboard.welcome': { 'zh-CN': '欢迎使用 AICenter - 你的 AI 运维控制中心', 'en-US': 'Welcome to AICenter - Your AI operations control center' },
  'dashboard.quickActions': { 'zh-CN': '快速操作', 'en-US': 'Quick Actions' },
  'dashboard.addServer': { 'zh-CN': '添加服务器', 'en-US': 'Add Server' },
  'dashboard.deployContainer': { 'zh-CN': '部署容器', 'en-US': 'Deploy Container' },
  'dashboard.createAgent': { 'zh-CN': '创建智能体', 'en-US': 'Create Agent' },
  'dashboard.addProvider': { 'zh-CN': '添加 Provider', 'en-US': 'Add Provider' },
  'dashboard.systemStatus': { 'zh-CN': '系统状态', 'en-US': 'System Status' },
  'dashboard.systemOnline': { 'zh-CN': 'AICenter 运行中。尚未连接任何服务器。', 'en-US': 'AICenter is running. No servers connected yet.' },
  'dashboard.systemHint': { 'zh-CN': '添加第一台服务器即可开始监控和管理基础设施。', 'en-US': 'Add your first server to start monitoring and managing infrastructure.' },

  'servers.title': { 'zh-CN': '服务器', 'en-US': 'Servers' },
  'servers.subtitle': { 'zh-CN': '管理你的 Linux 服务器并监控其状态', 'en-US': 'Manage your Linux servers and monitor their status' },
  'servers.refresh': { 'zh-CN': '刷新', 'en-US': 'Refresh' },
  'servers.add': { 'zh-CN': '添加服务器', 'en-US': 'Add Server' },
  'servers.empty': { 'zh-CN': '暂无服务器，点击"添加服务器"开始。', 'en-US': 'No servers yet. Click "Add Server" to get started.' },
  'servers.status.online': { 'zh-CN': '在线', 'en-US': 'Online' },
  'servers.status.offline': { 'zh-CN': '离线', 'en-US': 'Offline' },
  'servers.status.unknown': { 'zh-CN': '未知', 'en-US': 'Unknown' },
  'servers.connected': { 'zh-CN': '已连接', 'en-US': 'Connected' },
  'servers.disconnected': { 'zh-CN': '未连接', 'en-US': 'Disconnected' },
  'servers.never': { 'zh-CN': '从未', 'en-US': 'Never' },
  'servers.testConnection': { 'zh-CN': '测试连接', 'en-US': 'Test Connection' },
  'servers.testing': { 'zh-CN': '正在测试...', 'en-US': 'Testing...' },
  'servers.testSuccess': { 'zh-CN': '连接测试成功', 'en-US': 'Connection test successful' },
  'servers.testFailed': { 'zh-CN': '连接测试失败', 'en-US': 'Connection test failed' },
  'servers.copied': { 'zh-CN': 'SSH 命令已复制', 'en-US': 'SSH command copied' },
  'servers.confirmDelete': { 'zh-CN': '确定删除该服务器？', 'en-US': 'Delete this server?' },
  'servers.cancel': { 'zh-CN': '取消', 'en-US': 'Cancel' },
  'servers.delete': { 'zh-CN': '删除', 'en-US': 'Delete' },
  'servers.actions': { 'zh-CN': '操作', 'en-US': 'Actions' },
  'servers.edit': { 'zh-CN': '编辑', 'en-US': 'Edit' },
  'servers.addTitle': { 'zh-CN': '添加服务器', 'en-US': 'Add Server' },
  'servers.editTitle': { 'zh-CN': '编辑服务器', 'en-US': 'Edit Server' },
  'servers.basicInfo': { 'zh-CN': '基本信息', 'en-US': 'Basic Info' },
  'servers.name': { 'zh-CN': '服务器名称', 'en-US': 'Server Name' },
  'servers.namePlaceholder': { 'zh-CN': '例如：生产 Web 服务器', 'en-US': 'e.g., Production Web Server' },
  'servers.host': { 'zh-CN': '主机 / IP', 'en-US': 'Host / IP' },
  'servers.hostPlaceholder': { 'zh-CN': '192.168.1.100 或 server.example.com', 'en-US': '192.168.1.100 or server.example.com' },
  'servers.port': { 'zh-CN': '端口', 'en-US': 'Port' },
  'servers.username': { 'zh-CN': '用户名', 'en-US': 'Username' },
  'servers.auth': { 'zh-CN': '认证', 'en-US': 'Authentication' },
  'servers.authType': { 'zh-CN': '认证方式', 'en-US': 'Auth Type' },
  'servers.authSelect': { 'zh-CN': '选择认证方式', 'en-US': 'Select auth type' },
  'servers.password': { 'zh-CN': '密码', 'en-US': 'Password' },
  'servers.passwordPlaceholder': { 'zh-CN': '请输入密码', 'en-US': 'Enter password' },
  'servers.privateKey': { 'zh-CN': '私钥', 'en-US': 'Private Key' },
  'servers.privateKeyPlaceholder': { 'zh-CN': '粘贴你的 SSH 私钥...', 'en-US': 'Paste your SSH private key here...' },
  'servers.testResultTitle': { 'zh-CN': '连接测试结果', 'en-US': 'Connection Test Result' },
  'servers.systemInfoTitle': { 'zh-CN': '系统信息', 'en-US': 'System Info' },
  'servers.os': { 'zh-CN': '系统', 'en-US': 'OS' },
  'servers.hostname': { 'zh-CN': '主机名', 'en-US': 'Hostname' },
  'servers.kernel': { 'zh-CN': '内核', 'en-US': 'Kernel' },
  'servers.cpuCores': { 'zh-CN': 'CPU 核心', 'en-US': 'CPU Cores' },
  'servers.memoryGB': { 'zh-CN': '内存 (GB)', 'en-US': 'Memory (GB)' },
  'servers.timestamp': { 'zh-CN': '时间', 'en-US': 'Timestamp' },
  'servers.message': { 'zh-CN': '信息', 'en-US': 'Message' },
  'servers.sshBanner': { 'zh-CN': 'SSH Banner', 'en-US': 'SSH Banner' },

  'docker.title': { 'zh-CN': 'Docker', 'en-US': 'Docker' },
  'docker.subtitle': { 'zh-CN': '管理容器、镜像、卷、网络和 Compose 项目', 'en-US': 'Manage containers, images, volumes, networks, and compose projects' },
  'docker.connected': { 'zh-CN': '已连接', 'en-US': 'Connected' },
  'docker.connecting': { 'zh-CN': '连接中…', 'en-US': 'Connecting…' },
  'docker.refresh': { 'zh-CN': '刷新', 'en-US': 'Refresh' },
  'docker.hosts': { 'zh-CN': '主机', 'en-US': 'Hosts' },
  'docker.online': { 'zh-CN': '在线', 'en-US': 'online' },
  'docker.containers': { 'zh-CN': '容器', 'en-US': 'Containers' },
  'docker.images': { 'zh-CN': '镜像', 'en-US': 'Images' },
  'docker.volumes': { 'zh-CN': '卷', 'en-US': 'Volumes' },
  'docker.networks': { 'zh-CN': '网络', 'en-US': 'Networks' },
  'docker.compose': { 'zh-CN': 'Compose', 'en-US': 'Compose' },

  'agents.title': { 'zh-CN': '智能体', 'en-US': 'AI Agents' },
  'agents.subtitle': { 'zh-CN': '配置智能体、选择工具和权限策略，然后在对话中运行', 'en-US': 'Configure agents, choose tools and permission policy, then run them in a chat.' },
  'agents.refresh': { 'zh-CN': '刷新', 'en-US': 'Refresh' },
  'agents.create': { 'zh-CN': '新建智能体', 'en-US': 'Create Agent' },
  'agents.edit': { 'zh-CN': '编辑智能体', 'en-US': 'Edit Agent' },
  'agents.empty': { 'zh-CN': '暂无智能体，请先创建。', 'en-US': 'No agents yet. Create one to start.' },
  'agents.approvals': { 'zh-CN': '审批 ({n})', 'en-US': 'Approvals ({n})' },
  'agents.name': { 'zh-CN': '名称', 'en-US': 'Name' },
  'agents.description': { 'zh-CN': '描述', 'en-US': 'Description' },
  'agents.model': { 'zh-CN': '模型 (provider id)', 'en-US': 'Model (provider id)' },
  'agents.systemPrompt': { 'zh-CN': '系统提示词', 'en-US': 'System prompt' },
  'agents.permissionMode': { 'zh-CN': '权限模式', 'en-US': 'Permission mode' },
  'agents.availableTools': { 'zh-CN': '可用工具', 'en-US': 'Available tools' },
  'agents.requireApproval': { 'zh-CN': '需要审批的工具', 'en-US': 'Require approval for' },
  'agents.temperature': { 'zh-CN': '温度', 'en-US': 'Temperature' },
  'agents.maxTokens': { 'zh-CN': '最大令牌数', 'en-US': 'Max tokens' },
  'agents.maxIterations': { 'zh-CN': '最大迭代次数', 'en-US': 'Max iterations' },
  'agents.enabled': { 'zh-CN': '启用', 'en-US': 'Enabled' },
  'agents.disabled': { 'zh-CN': '禁用', 'en-US': 'Disabled' },
  'agents.enable': { 'zh-CN': '启用', 'en-US': 'Enable' },
  'agents.updated': { 'zh-CN': 'Agent 已更新', 'en-US': 'Agent updated' },
  'agents.created': { 'zh-CN': 'Agent 已创建', 'en-US': 'Agent created' },
  'agents.deleted': { 'zh-CN': 'Agent 已删除', 'en-US': 'Agent deleted' },
  'agents.confirmDelete': { 'zh-CN': '确认删除?', 'en-US': 'Confirm delete?' },
  'agents.column.name': { 'zh-CN': '智能体', 'en-US': 'Agent' },
  'agents.column.model': { 'zh-CN': '模型', 'en-US': 'Model' },
  'agents.column.tools': { 'zh-CN': 'Tools', 'en-US': 'Tools' },
  'agents.column.tempIter': { 'zh-CN': '温度 / 最大迭代', 'en-US': 'Temp / Max Iter' },
  'agents.column.actions': { 'zh-CN': '操作', 'en-US': 'Actions' },
  'agents.action.chat': { 'zh-CN': '对话', 'en-US': 'Chat' },
  'agents.action.edit': { 'zh-CN': '编辑', 'en-US': 'Edit' },
  'agents.action.delete': { 'zh-CN': '删除', 'en-US': 'Delete' },
  'agents.session.title': { 'zh-CN': 'Agent 会话', 'en-US': 'Agent Session' },
  'agents.session.close': { 'zh-CN': '关闭', 'en-US': 'Close' },
  'agents.session.newSession': { 'zh-CN': '新会话', 'en-US': 'New Session' },
  'agents.session.noSessions': { 'zh-CN': '暂无会话', 'en-US': 'No sessions' },
  'agents.session.untitled': { 'zh-CN': '未命名', 'en-US': 'untitled' },
  'agents.session.active': { 'zh-CN': '进行中', 'en-US': 'active' },
  'agents.session.run': { 'zh-CN': '运行', 'en-US': 'Run' },
  'agents.session.placeholder': { 'zh-CN': "Ask the agent... e.g. 'list servers' or 'restart nginx'", 'en-US': "Ask the agent... e.g. 'list servers' or 'restart nginx'" },
  'agents.session.outputHint': { 'zh-CN': 'Agent 输出会显示在这里', 'en-US': 'Agent output will appear here' },
  'agents.session.toolPlan': { 'zh-CN': '工具计划 / 结果:', 'en-US': 'Tool plan / results:' },
  'agents.session.inputPlaceholder': { 'zh-CN': "输入问题，例如：'list servers' 或 'restart nginx'", 'en-US': "Ask the agent... e.g. 'list servers' or 'restart nginx'" },
  'agents.notFound': { 'zh-CN': '未找到智能体', 'en-US': 'Agent not found' },
  'agents.approval.required': { 'zh-CN': '需要审批: {tool}', 'en-US': 'Approval required: {tool}' },
  'agents.approval.approved': { 'zh-CN': '已批准', 'en-US': 'Approved' },
  'agents.approval.rejected': { 'zh-CN': '已拒绝', 'en-US': 'Rejected' },
  'agents.approval.title': { 'zh-CN': '待审批', 'en-US': 'Pending Approvals' },
  'agents.approval.noPending': { 'zh-CN': 'No pending approvals', 'en-US': 'No pending approvals' },
  'agents.approval.tool': { 'zh-CN': '工具', 'en-US': 'Tool' },
  'agents.approval.risk': { 'zh-CN': '风险', 'en-US': 'Risk' },
  'agents.approval.requester': { 'zh-CN': '申请人', 'en-US': 'Requester' },
  'agents.approval.created': { 'zh-CN': '创建', 'en-US': 'Created' },
  'agents.approval.actions': { 'zh-CN': '操作', 'en-US': 'Actions' },
  'agents.approval.approve': { 'zh-CN': '批准', 'en-US': 'Approve' },
  'agents.approval.reject': { 'zh-CN': '拒绝', 'en-US': 'Reject' },
  'agents.role.user': { 'zh-CN': '用户', 'en-US': 'User' },
  'agents.role.assistant': { 'zh-CN': '助手', 'en-US': 'Assistant' },
  'agents.role.tool': { 'zh-CN': '工具', 'en-US': 'Tool' },
  'agents.mode.allowAll': { 'zh-CN': '全部允许 (allow_all)', 'en-US': 'Allow All (allow_all)' },
  'agents.mode.denyAll': { 'zh-CN': '全部拒绝 (deny_all)', 'en-US': 'Deny All (deny_all)' },
  'agents.mode.manual': { 'zh-CN': '人工审批 (manual)', 'en-US': 'Manual Approval (manual)' },
  'agents.modelWithId': { 'zh-CN': '{name} ({id})', 'en-US': '{name} ({id})' },

  'approvals.title': { 'zh-CN': '待审批', 'en-US': 'Approvals' },
  'approvals.subtitle': { 'zh-CN': '审查并批准高风险操作', 'en-US': 'Review and approve high-risk operations' },
  'approvals.empty': { 'zh-CN': '暂无待审批项。', 'en-US': 'No pending approvals.' },
  'approvals.hint': { 'zh-CN': '当 AI 智能体请求执行高风险操作时，会在这里展示供你审核。', 'en-US': 'When AI agents request high-risk operations, they will appear here for your review.' },

  'audit.title': { 'zh-CN': '审计日志', 'en-US': 'Audit Log' },
  'audit.subtitle': { 'zh-CN': '所有操作与变更的完整历史记录', 'en-US': 'Complete history of all operations and changes' },
  'audit.empty': { 'zh-CN': '暂无审计日志。', 'en-US': 'No audit logs yet.' },
  'audit.hint': { 'zh-CN': '所有操作都会被记录在这里，用于合规与安全审计。', 'en-US': 'All operations will be recorded here for compliance and security.' },

  'ai.title': { 'zh-CN': 'AI 模型', 'en-US': 'AI Providers' },
  'ai.subtitle': { 'zh-CN': '配置 AI Provider，供智能体和其他功能使用', 'en-US': 'Configure AI providers and models for Agent operations' },
  'ai.refresh': { 'zh-CN': '刷新', 'en-US': 'Refresh' },
  'ai.addProvider': { 'zh-CN': '添加 Provider', 'en-US': 'Add Provider' },
  'ai.empty': { 'zh-CN': '暂无 AI Provider，请先添加。', 'en-US': 'No AI providers yet. Add one to get started.' },
  'ai.column.name': { 'zh-CN': '名称', 'en-US': 'Name' },
  'ai.column.address': { 'zh-CN': '地址', 'en-US': 'Address' },
  'ai.column.apiKey': { 'zh-CN': 'API Key', 'en-US': 'API Key' },
  'ai.column.enabled': { 'zh-CN': '启用', 'en-US': 'Enabled' },
  'ai.column.actions': { 'zh-CN': '操作', 'en-US': 'Actions' },
  'ai.action.edit': { 'zh-CN': '编辑', 'en-US': 'Edit' },
  'ai.action.chat': { 'zh-CN': '聊天', 'en-US': 'Chat' },
  'ai.action.delete': { 'zh-CN': '删除', 'en-US': 'Delete' },
  'ai.confirmDelete': { 'zh-CN': '确认删除此 Provider？', 'en-US': 'Delete this provider?' },
  'ai.confirmDeleteHint': { 'zh-CN': '关联模型也会被删除', 'en-US': 'Associated models will also be deleted' },
  'ai.notSet': { 'zh-CN': '未设置', 'en-US': 'Not set' },
  'ai.noModels': { 'zh-CN': 'No models', 'en-US': 'No models' },
  'ai.default': { 'zh-CN': '默认', 'en-US': 'Default' },
  'ai.modelWithId': { 'zh-CN': '{name} ({id})', 'en-US': '{name} ({id})' },

  'common.confirm': { 'zh-CN': '确定', 'en-US': 'Confirm' },
  'common.cancel': { 'zh-CN': '取消', 'en-US': 'Cancel' },
  'common.save': { 'zh-CN': '保存', 'en-US': 'Save' },
  'common.delete': { 'zh-CN': '删除', 'en-US': 'Delete' },
  'common.edit': { 'zh-CN': '编辑', 'en-US': 'Edit' },
  'common.create': { 'zh-CN': '创建', 'en-US': 'Create' },
  'common.update': { 'zh-CN': '更新', 'en-US': 'Update' },
  'common.refresh': { 'zh-CN': '刷新', 'en-US': 'Refresh' },
  'common.actions': { 'zh-CN': '操作', 'en-US': 'Actions' },
  'common.status': { 'zh-CN': '状态', 'en-US': 'Status' },
  'common.name': { 'zh-CN': '名称', 'en-US': 'Name' },
  'common.type': { 'zh-CN': '类型', 'en-US': 'Type' },
  'common.description': { 'zh-CN': '描述', 'en-US': 'Description' },
  'common.enabled': { 'zh-CN': '启用', 'en-US': 'Enabled' },
  'common.disabled': { 'zh-CN': '停用', 'en-US': 'Disabled' },
  'common.loading': { 'zh-CN': '加载中...', 'en-US': 'Loading...' },
  'common.success': { 'zh-CN': '成功', 'en-US': 'Success' },
  'common.failed': { 'zh-CN': '失败', 'en-US': 'Failed' },

  'auth.403': { 'zh-CN': '403 — 无权访问', 'en-US': '403 — Forbidden' },
  'auth.403Hint': { 'zh-CN': '你的角色无权访问该页面。', 'en-US': 'Your role does not have permission to access this page.' },
  'auth.back': { 'zh-CN': '返回', 'en-US': 'Go Back' },

  'settings.title': { 'zh-CN': '设置', 'en-US': 'Settings' },
  'settings.subtitle': { 'zh-CN': '配置 AICenter 偏好设置', 'en-US': 'Configure AICenter preferences' },
  'settings.appearance': { 'zh-CN': '外观', 'en-US': 'Appearance' },
  'settings.theme': { 'zh-CN': '主题:', 'en-US': 'Theme:' },
  'settings.lightMode': { 'zh-CN': '浅色模式', 'en-US': 'Light Mode' },
  'settings.darkMode': { 'zh-CN': '深色模式', 'en-US': 'Dark Mode' },
  'settings.account': { 'zh-CN': '账户', 'en-US': 'Account' },
  'settings.username': { 'zh-CN': '用户名:', 'en-US': 'Username:' },
  'settings.email': { 'zh-CN': '邮箱:', 'en-US': 'Email:' },
  'settings.role': { 'zh-CN': '角色:', 'en-US': 'Role:' },
  'settings.system': { 'zh-CN': '系统', 'en-US': 'System' },
  'settings.version': { 'zh-CN': 'AICenter v1.0.0 - AI 运维控制中心', 'en-US': 'AICenter v1.0.0 - AI Operations Control Center' },

  'tasks.title': { 'zh-CN': '任务', 'en-US': 'Tasks' },
  'tasks.subtitle': { 'zh-CN': '定时安排和管理自动化运维任务', 'en-US': 'Schedule and manage automated operations tasks' },
  'tasks.create': { 'zh-CN': '创建任务', 'en-US': 'Create Task' },
  'tasks.empty': { 'zh-CN': '暂无任务。', 'en-US': 'No tasks yet.' },
  'tasks.hint': { 'zh-CN': '创建定时任务来实现自动化运维。', 'en-US': 'Create scheduled tasks to automate operations.' },

  'batch.refreshServers': { 'zh-CN': '刷新服务器', 'en-US': 'Refresh Servers' },
  'batch.selected': { 'zh-CN': '已选 {n} 台 · 命令超时 {t}s', 'en-US': '{n} selected · timeout {t}s' },
  'batch.title': { 'zh-CN': '批量执行命令', 'en-US': 'Batch Execute Command' },
  'batch.execute': { 'zh-CN': '执行', 'en-US': 'Execute' },
  'batch.executing': { 'zh-CN': '执行中...', 'en-US': 'Executing...' },
  'batch.server': { 'zh-CN': '服务器', 'en-US': 'Server' },
  'batch.address': { 'zh-CN': '地址', 'en-US': 'Address' },
  'batch.status': { 'zh-CN': '状态', 'en-US': 'Status' },
  'batch.duration': { 'zh-CN': '耗时', 'en-US': 'Duration' },
  'batch.exitCode': { 'zh-CN': '退出码', 'en-US': 'Exit Code' },
  'batch.output': { 'zh-CN': '输出', 'en-US': 'Output' },
  'batch.success': { 'zh-CN': '成功', 'en-US': 'Success' },
  'batch.failed': { 'zh-CN': '失败', 'en-US': 'Failed' },
  'batch.serverList': { 'zh-CN': '服务器列表 ({n})', 'en-US': 'Server List ({n})' },
  'batch.results': { 'zh-CN': '结果 ({n})', 'en-US': 'Results ({n})' },
  'batch.running': { 'zh-CN': '正在执行…', 'en-US': 'Executing…' },
  'batch.enterCommand': { 'zh-CN': '请输入命令', 'en-US': 'Please enter a command' },
  'batch.selectServers': { 'zh-CN': '请选择服务器', 'en-US': 'Please select servers' },
  'batch.executeFailed': { 'zh-CN': '批量执行失败', 'en-US': 'Batch execution failed' },

  'server.detail.loading': { 'zh-CN': '加载服务器失败', 'en-US': 'Failed to load server' },
  'server.detail.back': { 'zh-CN': '返回', 'en-US': 'Back' },
  'server.detail.refresh': { 'zh-CN': '刷新', 'en-US': 'Refresh' },
  'server.detail.openTerminal': { 'zh-CN': '打开终端', 'en-US': 'Open Terminal' },
  'server.detail.overview': { 'zh-CN': '概览', 'en-US': 'Overview' },
  'server.detail.terminal': { 'zh-CN': '终端', 'en-US': 'Terminal' },
  'server.detail.host': { 'zh-CN': '主机', 'en-US': 'Host' },
  'server.detail.username': { 'zh-CN': '用户名', 'en-US': 'Username' },
  'server.detail.authType': { 'zh-CN': '认证方式', 'en-US': 'Auth Type' },
  'server.detail.status': { 'zh-CN': '状态', 'en-US': 'Status' },
  'server.detail.agent': { 'zh-CN': 'Agent', 'en-US': 'Agent' },
  'server.detail.connected': { 'zh-CN': '已连接', 'en-US': 'Connected' },
  'server.detail.disconnected': { 'zh-CN': '未连接', 'en-US': 'Disconnected' },
  'server.detail.tags': { 'zh-CN': '标签', 'en-US': 'Tags' },
  'server.detail.distribution': { 'zh-CN': '发行版', 'en-US': 'Distribution' },
  'server.detail.kernel': { 'zh-CN': '内核', 'en-US': 'Kernel' },
  'server.detail.architecture': { 'zh-CN': '架构', 'en-US': 'Architecture' },
  'server.detail.hostname': { 'zh-CN': '主机名', 'en-US': 'Hostname' },
  'server.detail.notFound': { 'zh-CN': '服务器不存在', 'en-US': 'Server not found' },
  'server.detail.startPtyHint': { 'zh-CN': '点击「打开终端」启动一个 PTY 会话。', 'en-US': 'Click "Open Terminal" to start a PTY session.' },
  'server.detail.openTerminalFailed': { 'zh-CN': '打开终端失败', 'en-US': 'Failed to open terminal' },

  'monitor.title': { 'zh-CN': '监控告警', 'en-US': 'Monitoring & Alerts' },
  'monitor.subtitle': { 'zh-CN': '指标采集、阈值告警与事件管理', 'en-US': 'Metric collection, threshold alerts, and event management' },
  'monitor.refresh': { 'zh-CN': '刷新', 'en-US': 'Refresh' },
  'monitor.overview': { 'zh-CN': '概览', 'en-US': 'Overview' },
  'monitor.alertEvents': { 'zh-CN': '告警事件 ({n})', 'en-US': 'Alert Events ({n})' },
  'monitor.alertRules': { 'zh-CN': '告警规则 ({n})', 'en-US': 'Alert Rules ({n})' },
  'monitor.firingAlerts': { 'zh-CN': '⚠ 当前有 {n} 条 firing 告警待处理', 'en-US': '⚠ {n} firing alert(s) pending' },
  'monitor.noData': { 'zh-CN': '暂无指标数据，等待采集循环写入', 'en-US': 'No metrics data yet, waiting for collection cycle' },
  'monitor.server': { 'zh-CN': '服务器: {id}', 'en-US': 'Server: {id}' },
  'monitor.column.severity': { 'zh-CN': '级别', 'en-US': 'Severity' },
  'monitor.column.status': { 'zh-CN': '状态', 'en-US': 'Status' },
  'monitor.column.server': { 'zh-CN': '服务器', 'en-US': 'Server' },
  'monitor.column.message': { 'zh-CN': '信息', 'en-US': 'Message' },
  'monitor.column.triggeredAt': { 'zh-CN': '触发时间', 'en-US': 'Triggered At' },
  'monitor.column.actions': { 'zh-CN': '操作', 'en-US': 'Actions' },
  'monitor.ack': { 'zh-CN': '确认', 'en-US': 'Acknowledge' },
  'monitor.acked': { 'zh-CN': '已确认', 'en-US': 'Acknowledged' },
  'monitor.createRule': { 'zh-CN': '新建规则', 'en-US': 'Create Rule' },
  'monitor.column.name': { 'zh-CN': '名称', 'en-US': 'Name' },
  'monitor.column.metric': { 'zh-CN': '指标', 'en-US': 'Metric' },
  'monitor.column.condition': { 'zh-CN': '条件', 'en-US': 'Condition' },
  'monitor.column.duration': { 'zh-CN': '持续(s)', 'en-US': 'Duration(s)' },
  'monitor.column.enabled': { 'zh-CN': '启用', 'en-US': 'Enabled' },
  'monitor.column.cooldown': { 'zh-CN': '冷却(s)', 'en-US': 'Cooldown(s)' },
  'monitor.column.yes': { 'zh-CN': '是', 'en-US': 'Yes' },
  'monitor.column.no': { 'zh-CN': '否', 'en-US': 'No' },
  'monitor.edit': { 'zh-CN': '编辑', 'en-US': 'Edit' },
  'monitor.delete': { 'zh-CN': '删除', 'en-US': 'Delete' },
  'monitor.ruleCreated': { 'zh-CN': '规则已创建', 'en-US': 'Rule created' },
  'monitor.ruleUpdated': { 'zh-CN': '规则已更新', 'en-US': 'Rule updated' },
  'monitor.ruleDeleted': { 'zh-CN': '规则已删除', 'en-US': 'Rule deleted' },
  'monitor.confirmDeleteRule': { 'zh-CN': '确认删除该规则？', 'en-US': 'Delete this rule?' },
  'monitor.editRule': { 'zh-CN': '编辑告警规则', 'en-US': 'Edit Alert Rule' },
  'monitor.createRuleTitle': { 'zh-CN': '新建告警规则', 'en-US': 'Create Alert Rule' },
  'monitor.ruleName': { 'zh-CN': '规则名称', 'en-US': 'Rule Name' },
  'monitor.ruleNamePlaceholder': { 'zh-CN': '如 CPU 过高', 'en-US': 'e.g. High CPU' },
  'monitor.metric': { 'zh-CN': '指标', 'en-US': 'Metric' },
  'monitor.condition': { 'zh-CN': '条件', 'en-US': 'Condition' },
  'monitor.threshold': { 'zh-CN': '阈值', 'en-US': 'Threshold' },
  'monitor.durationSeconds': { 'zh-CN': '持续时间（秒，0 = 立即）', 'en-US': 'Duration (seconds, 0 = immediate)' },
  'monitor.severity': { 'zh-CN': '级别', 'en-US': 'Severity' },
  'monitor.cooldownSeconds': { 'zh-CN': '冷却时间（秒）', 'en-US': 'Cooldown (seconds)' },
  'monitor.enable': { 'zh-CN': '启用', 'en-US': 'Enable' },
  'monitor.enterName': { 'zh-CN': '请输入名称', 'en-US': 'Please enter a name' },

  'notifications.title': { 'zh-CN': '通知中心', 'en-US': 'Notification Center' },
  'notifications.subtitle': { 'zh-CN': '管理通知渠道、模板与投递日志；告警与审批事件将按模板自动推送。', 'en-US': 'Manage notification channels, templates, and delivery logs; alerts and approval events are pushed automatically by template.' },
  'notifications.channels': { 'zh-CN': '通知渠道', 'en-US': 'Channels' },
  'notifications.templates': { 'zh-CN': '通知模板', 'en-US': 'Templates' },
  'notifications.logs': { 'zh-CN': '投递日志', 'en-US': 'Delivery Logs' },
  'notifications.testSend': { 'zh-CN': '测试发送', 'en-US': 'Test Send' },
  'notifications.newChannel': { 'zh-CN': '新建渠道', 'en-US': 'New Channel' },
  'notifications.editChannel': { 'zh-CN': '编辑渠道', 'en-US': 'Edit Channel' },
  'notifications.refresh': { 'zh-CN': '刷新', 'en-US': 'Refresh' },
  'notifications.column.name': { 'zh-CN': '名称', 'en-US': 'Name' },
  'notifications.column.type': { 'zh-CN': '类型', 'en-US': 'Type' },
  'notifications.column.status': { 'zh-CN': '状态', 'en-US': 'Status' },
  'notifications.column.config': { 'zh-CN': '配置预览', 'en-US': 'Config Preview' },
  'notifications.column.actions': { 'zh-CN': '操作', 'en-US': 'Actions' },
  'notifications.edit': { 'zh-CN': '编辑', 'en-US': 'Edit' },
  'notifications.delete': { 'zh-CN': '删除', 'en-US': 'Delete' },
  'notifications.enable': { 'zh-CN': '启用', 'en-US': 'Enable' },
  'notifications.disable': { 'zh-CN': '禁用', 'en-US': 'Disable' },
  'notifications.saved': { 'zh-CN': '已保存', 'en-US': 'Saved' },
  'notifications.deleted': { 'zh-CN': '已删除', 'en-US': 'Deleted' },
  'notifications.confirmDeleteChannel': { 'zh-CN': '确认删除该渠道？', 'en-US': 'Delete this channel?' },
  'notifications.type': { 'zh-CN': '类型', 'en-US': 'Type' },
  'notifications.configJson': { 'zh-CN': '配置 (JSON)', 'en-US': 'Config (JSON)' },
  'notifications.configHint': { 'zh-CN': 'webhook: {url, token}; email/sms: {to}; im: {token}', 'en-US': 'webhook: {url, token}; email/sms: {to}; im: {token}' },
  'notifications.nameRequired': { 'zh-CN': '必填', 'en-US': 'Required' },
  'notifications.configMustBeJson': { 'zh-CN': '配置必须是合法 JSON', 'en-US': 'Config must be valid JSON' },
  'notifications.newTemplate': { 'zh-CN': '新建模板', 'en-US': 'New Template' },
  'notifications.editTemplate': { 'zh-CN': '编辑模板', 'en-US': 'Edit Template' },
  'notifications.confirmDeleteTemplate': { 'zh-CN': '确认删除？', 'en-US': 'Confirm delete?' },
  'notifications.column.eventType': { 'zh-CN': '事件类型', 'en-US': 'Event Type' },
  'notifications.column.subject': { 'zh-CN': '标题', 'en-US': 'Subject' },
  'notifications.name': { 'zh-CN': '名称', 'en-US': 'Name' },
  'notifications.eventType': { 'zh-CN': '事件类型', 'en-US': 'Event Type' },
  'notifications.templateSubject': { 'zh-CN': '标题', 'en-US': 'Subject' },
  'notifications.titlePlaceholder': { 'zh-CN': '[AICenter 告警] {{.Title}}', 'en-US': '[AICenter Alert] {{.Title}}' },
  'notifications.titleHint': { 'zh-CN': '支持 {{.Title}} 等占位符', 'en-US': 'Supports {{.Title}} and other placeholders' },
  'notifications.body': { 'zh-CN': '正文', 'en-US': 'Body' },
  'notifications.bodyHint': { 'zh-CN': '可用变量: {{.Title}} {{.Severity}} {{.Message}} {{.Data.xxx}}', 'en-US': 'Available variables: {{.Title}} {{.Severity}} {{.Message}} {{.Data.xxx}}' },
  'notifications.channelTypes': { 'zh-CN': '渠道类型 (JSON 数组)', 'en-US': 'Channel Types (JSON array)' },
  'notifications.channelTypesPlaceholder': { 'zh-CN': '["console","webhook"]', 'en-US': '["console","webhook"]' },
  'notifications.all': { 'zh-CN': '全部', 'en-US': 'All' },
  'notifications.sent': { 'zh-CN': '已发送', 'en-US': 'Sent' },
  'notifications.failed': { 'zh-CN': '失败', 'en-US': 'Failed' },
  'notifications.column.time': { 'zh-CN': '时间', 'en-US': 'Time' },
  'notifications.column.event': { 'zh-CN': '事件', 'en-US': 'Event' },
  'notifications.column.channel': { 'zh-CN': '渠道', 'en-US': 'Channel' },
  'notifications.column.error': { 'zh-CN': '错误', 'en-US': 'Error' },
  'notifications.level': { 'zh-CN': '级别', 'en-US': 'Level' },
  'notifications.message': { 'zh-CN': '正文', 'en-US': 'Message' },
  'notifications.data': { 'zh-CN': '附加数据 (JSON)', 'en-US': 'Additional Data (JSON)' },
  'notifications.dataPlaceholder': { 'zh-CN': '如 {"server_id":"srv-1","value":"96.5"}', 'en-US': 'e.g. {"server_id":"srv-1","value":"96.5"}' },
  'notifications.dataHint': { 'zh-CN': '如 {"server_id":"srv-1","value":"96.5"}', 'en-US': 'e.g. {"server_id":"srv-1","value":"96.5"}' },
  'notifications.sendTest': { 'zh-CN': '发送测试', 'en-US': 'Send Test' },
  'notifications.testSent': { 'zh-CN': '已触发发送，请到投递日志查看结果', 'en-US': 'Test sent, check delivery logs for results' },
  'notifications.dataMustBeJson': { 'zh-CN': 'data 必须是合法 JSON', 'en-US': 'data must be valid JSON' },
  'notifications.alertFired': { 'zh-CN': '告警触发', 'en-US': 'Alert Fired' },
  'notifications.approvalRequested': { 'zh-CN': '审批请求', 'en-US': 'Approval Requested' },
  'notifications.approvalResolved': { 'zh-CN': '审批结果', 'en-US': 'Approval Resolved' },
  'notifications.webhook': { 'zh-CN': 'Webhook', 'en-US': 'Webhook' },
  'notifications.email': { 'zh-CN': '邮件', 'en-US': 'Email' },
  'notifications.sms': { 'zh-CN': '短信', 'en-US': 'SMS' },
  'notifications.im': { 'zh-CN': 'IM', 'en-US': 'IM' },
  'notifications.console': { 'zh-CN': '控制台 (开发)', 'en-US': 'Console (dev)' },
};

const getInitialLocale = (): Locale =>
  (localStorage.getItem('locale') as Locale) || 'zh-CN';

// Build a translation function bound to a specific locale. We return a fresh
// function instance whenever the locale changes so that components selecting
// `t` from the store (via `useUIStore((s) => s.t)`) re-render on language switch
// without needing a per-component locale subscription.
function makeT(locale: Locale): UIState['t'] {
  return (key: string, fallback?: string) => {
    const entry = dictionary[key];
    if (!entry) return fallback || key;
    return entry[locale] || fallback || entry['en-US'] || key;
  };
}

export interface UIState {
  sidebarCollapsed: boolean;
  theme: 'light' | 'dark';
  locale: Locale;
  toggleSidebar: () => void;
  setTheme: (theme: 'light' | 'dark') => void;
  toggleTheme: () => void;
  setLocale: (locale: Locale) => void;
  toggleLocale: () => void;
  t: (key: string, fallback?: string) => string;
}

export const useUIStore = create<UIState>()((set) => ({
  sidebarCollapsed: false,
  theme: (localStorage.getItem('theme') as 'light' | 'dark') || 'light',
  locale: getInitialLocale(),
  toggleSidebar: () => set((state) => ({ sidebarCollapsed: !state.sidebarCollapsed })),
  setTheme: (theme) => {
    localStorage.setItem('theme', theme);
    document.body.setAttribute('arco-theme', theme);
    set({ theme });
  },
  toggleTheme: () =>
    set((state) => {
      const theme = state.theme === 'light' ? 'dark' : 'light';
      localStorage.setItem('theme', theme);
      document.body.setAttribute('arco-theme', theme);
      return { theme };
    }),
  setLocale: (locale) => {
    localStorage.setItem('locale', locale);
    set({ locale, t: makeT(locale) });
  },
  toggleLocale: () =>
    set((state) => {
      const locale = state.locale === 'zh-CN' ? 'en-US' : 'zh-CN';
      localStorage.setItem('locale', locale);
      return { locale, t: makeT(locale) };
    }),
  t: makeT(getInitialLocale()),
}));

/** Reactive translation hook — re-renders the component when locale changes. */
export function useT(): UIState['t'] {
  const locale = useUIStore((s) => s.locale);
  return React.useCallback(
    (key: string, fallback?: string) => {
      const entry = dictionary[key];
      if (!entry) return fallback || key;
      return entry[locale] || fallback || entry['en-US'] || key;
    },
    [locale],
  );
}
